version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/conf.d/default.conf:ro
      - ./static:/usr/share/ngnix/static:ro
      - ./html:/usr/share/ngnix/html:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
